// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// Oauth2clientsColumns holds the columns for the "oauth2clients" table.
	Oauth2clientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "secret", Type: field.TypeString},
		{Name: "domain", Type: field.TypeString},
	}
	// Oauth2clientsTable holds the schema information for the "oauth2clients" table.
	Oauth2clientsTable = &schema.Table{
		Name:       "oauth2clients",
		Columns:    Oauth2clientsColumns,
		PrimaryKey: []*schema.Column{Oauth2clientsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		Oauth2clientsTable,
	}
)

func init() {
}
