// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/byebyebymyai/oauth2-api/ent/oauth2client"
	"github.com/byebyebymyai/oauth2-api/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oauth2clientMixin := schema.Oauth2Client{}.Mixin()
	oauth2clientMixinFields0 := oauth2clientMixin[0].Fields()
	_ = oauth2clientMixinFields0
	oauth2clientFields := schema.Oauth2Client{}.Fields()
	_ = oauth2clientFields
	// oauth2clientDescSecret is the schema descriptor for secret field.
	oauth2clientDescSecret := oauth2clientFields[0].Descriptor()
	// oauth2client.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	oauth2client.SecretValidator = oauth2clientDescSecret.Validators[0].(func(string) error)
	// oauth2clientDescDomain is the schema descriptor for domain field.
	oauth2clientDescDomain := oauth2clientFields[1].Descriptor()
	// oauth2client.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	oauth2client.DomainValidator = oauth2clientDescDomain.Validators[0].(func(string) error)
	// oauth2clientDescID is the schema descriptor for id field.
	oauth2clientDescID := oauth2clientMixinFields0[0].Descriptor()
	// oauth2client.DefaultID holds the default value on creation for the id field.
	oauth2client.DefaultID = oauth2clientDescID.Default.(func() uuid.UUID)
}
