// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Oauth2Client is the predicate function for oauth2client builders.
type Oauth2Client func(*sql.Selector)
